# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        http-only: true

knife4j:
  enable: true
  setting:
    custom-code: 500
    enable-footer-custom: false
    
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: train-boot
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

train:
  xss:
    enabled: true
    exclude-urls:
      - /test/**
  security:
    # 2小时过期
    access-token-expire: 7200
    # 14天过期
    refresh-token-expire: 1209600

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.train.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
